### ISSUE TITLE
cursor hard to see?

### ISSUE THREAD

**Issue by mjhoy** [mswift42/warm-night-theme#5]
I'm not sure if this is just an issue for my setup. But I find the cursor extremely hard to see.

Screenshot:

![screen shot 2017-06-08 at 16 15 50](https://user-images.githubusercontent.com/106337/26951161-d139b98c-4c65-11e7-8f4e-174cba886f83.png)

Am I just getting old?

Emacs 25.2, installed via homebrew on OSX 10.12, `--with-cocoa`.

**Comment by mswift42** [comment]
Sorry, I'm replying so late.

If you want to only change the cursor colour, you can either

- Fork warm-night (which you have already done) and customise the cursor color (line 73).

- Add the line `(set-cursor-color "#yourcolorhere")` to your init.el after the `load-theme` call to warm-night.

I don't want to change the cursor colour for all users, because most seem to be happy with the status quo. 

Thanks.

**Comment by mjhoy** [comment]
Thanks!
